### ISSUE TITLE
Judges' view should monitor device heartbeats

### ISSUE THREAD

**Issue by nwf** [cmukgb/ctfws-timer-page#3]
Our jail timer devices report in periodically using the MQTT topics `ctfws/dev/${DEVICENAME}/beat`.  (See the protocol docs for what exactly they publish.)  To get some notification if/when devices crash, it'd be nice if the judges view had indicators of freshness of last reported heartbeat or something.

**Comment by michaelfelixmurphy** [comment]
I am working on a sort of indirect solution for this. I'm adding a Broker tab to the judges' page that will show the entire MQTT topic tree and the current values. This should be a very useful debugging tool, and will allow us to see the general status of things (including devices) with no UI changes.

I do still intend to add the Devices tab and it should be relatively easy once I have the Broker tab done.

The only issue is that currently the web app subscribes anonymously and not all topics are publicly visible. This means the topic tree on the judges' page will be incomplete. Could we consider making all topics public? Or do we want to make a new user for whom that is true to use on the judges' side of the web app? I hesitate to use ctfwsmaster because the password will almost certainly have to be in the judge.html source in plaintext. Thoughts?

(A prototype of the Broker tab is currently deployed but broken. Working on a fix now. Also it will eventually be a user friendly tree rather than literal JSON output.)

**Comment by nwf** [comment]
Currently, I think we are not using any of the nominally private topics, are we?  For the moment I'd not worry about it.  Going forward, there's probably no harm in asking the judge to enter the `ctfwsmaster` password for authenticated access, tho', if we go there?  (Or using the `ctfwsmaster` password for authenticating judges, in general?)

**Comment by michaelfelixmurphy** [comment]
I agree with not worrying about it too much. I made a few changes to the acl on the KGB server to make it a bit simpler. I also fixed a typo you had: "ctfws/timestamp" -> "ctfws/timesync". You may want to copy the changes to the example acl on your website.

**Comment by nwf** [comment]
Thanks; typos fixed on website.  The broker view is shiny. :)

**Comment by michaelfelixmurphy** [comment]
This has been implemented in the Devices tab. For now I just show the beat information verbatim. I can probably display it a bit more nicely (local time, time since last beat). I've noted that myself. If you have any ideas, let me know, or open a new issue. For now, I'll close this one.
