### ISSUE TITLE
Cheatsheet link 404

### ISSUE THREAD

**Issue by nwf** [cmukgb/ctfws-timer-page#4]
https://www.dropbox.com/s/pq6gpsnode1pcl3/CtFwS%20Cheatsheet.pdf?raw=1 is no more, it seems. :(

**Comment by timparenti** [comment]
This is the line that would need to change to fix the broken link:
https://github.com/cmukgb/ctfws-timer-web/blob/40e9c41545c12d689fb834b1f990a2b063a8c357/templates/base.html#L236

This should probably live in some known place on the new server, and possibly even be checked into [cmukgb/ctfws](https://github.com/cmukgb/ctfws) as they are effectively a shorthand of the rules.

I've just poked senior members of the current Executive Board who might be able to assist with this.

**Comment by nwf** [comment]
We've started using the MQTT broker's persistent database for the handbook URL... would it make sense to also use it to publish the cheatsheet in a similar way?  At the `ctfws/rules/cheatsheet/pdf` topic or somesuch?

**Comment by timparenti** [comment]
I think that's probably a desirable longer-term solution.  If you can whip up the appropriate support on [ctfws-host-daemons](https://github.com/cmukgb/ctfws-host-daemons) and a matching PR here, @nwf, that'd be great.

Otherwise, I'll just plan to drop a static file in a known location and link it here to resolve this issue, and open a new one for eventual cheatsheet support on the broker.  I already have a candidate file for Spring 2019, since the rules haven't substantively changed since February 2017.

**Comment by nwf** [comment]
That should be viable.  I will make the handbook one do both.  What path on the webserver do you want to host the .pdf?

**Comment by timparenti** [comment]
@nwf I've just put a recent version of the file (likely close to final for Spring 2019, for the aforementioned reasons) at http://www.cmukgb.org/ctfws/cheatsheet.pdf.  And it looks like that's the URL you've [already used on ctfws-host-daemons](https://github.com/cmukgb/ctfws-host-daemons/commit/a4cb4aada32da9dca6ead44b6862a73563626965#diff-6e17036124d51b5fe30e6e665c74b707R33).

**Comment by nwf** [comment]
Hm.  Do we want to ship just a single instance to users vs. the "print this duplex and extract three" rendering?

**Comment by timparenti** [comment]
I agree that that would be better, but that's ultimately up to how Exec creates the file.  Either way, it's no longer an issue with this repo.
